# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 283f2d7e9659d2438b08b079508530b768002471a7298dad798f82f4d41514a91f44c32950ade4d2e6f1226fa5cbbc2ebfbe14ed3b409cb10d0c9d22baf8c1f0

test:
  secret_key_base: 3c8b23d1525b1f6608f065277c9a57a1ebc0c9c29487687237136f70f7b9b9c451e0c34d2aef4a8110d2e1aac13bf3cc6a6c332ff14eb3dd367280d477acf3ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
