development:
  mysql41: 9306
test:
  mysql41: 9307
production:
  pid_file: /home/deployer/ask/shared/tmp/searchd.pid
  indices_location: /home/deployer/ask/shared/db/sphinx
  configuration_file: /home/deployer/ask/shared/production.sphinx.conf
  binlog_path: /home/deployer/ask/shared/binlog